export const actionTypes = {
  ADD_TO_COMPARE_PRODUCT: "ADD_TO_COMPARE_PRODUCT",
  REMOVE_COMPARE_PRODUCT: "REMOVE_COMPARE_PRODUCT",
  SELECT_FILTER_PRODUCT: "SELECT_FILTER_PRODUCT",
  SET_FILTER_PRODUCT: "SET_FILTER_PRODUCT",
  RESET_FILTER_PRODUCT: "RESET_FILTER_PRODUCT"
};

export default actionTypes;
