export const actionTypes = {
  QUANTITY_INCREMENT: "QUANTITY_INCREMENT",
  QUANTITY_DECREMENT: "QUANTITY_DECREMENT",

  GET_CATEGORY_REQUEST: "GET_CATEGORY_REQUEST",
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  GET_CATEGORY_FAILURE: "GET_CATEGORY_FAILURE",

  GET_CATEGORIES_REQUEST: "GET_CATEGORIES_REQUEST",
  GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
  GET_CATEGORIES_FAILURE: "GET_CATEGORIES_FAILURE",

  GET_CATEGORY_PRODUCTS_REQUEST: "GET_CATEGORY_PRODUCTS_REQUEST",
  GET_CATEGORY_PRODUCTS_SUCCESS: "GET_CATEGORY_PRODUCTS_SUCCESS",
  GET_CATEGORY_PRODUCTS_FAILURE: "GET_CATEGORY_PRODUCTS_FAILURE",

  GET_PRODUCT_REQUEST: "GET_PRODUCT_REQUEST",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
  GET_PRODUCT_FAILURE: "GET_PRODUCT_FAILURE",

  GET_SIMILAR_PRODUCT_REQUEST: "GET_SIMILAR_PRODUCT_REQUEST",
  GET_SIMILAR_PRODUCT_SUCCESS: "GET_SIMILAR_PRODUCT_SUCCESS",
  GET_SIMILAR_PRODUCT_FAILURE: "GET_SIMILAR_PRODUCT_FAILURE",

  SEARCH_PRODUCT_REQUEST: "SEARCH_PRODUCT_REQUEST",
  SEARCH_PRODUCT_SUCCESS: "SEARCH_PRODUCT_SUCCESS",
  SEARCH_PRODUCT_FAILURE: "SEARCH_PRODUCT_FAILURE",

  SELECTED_PRODUCT_CATEGORY: "SELECTED_PRODUCT_CATEGORY",
  SELECT_PRODUCT_LANGUAGE: "SELECT_PRODUCT_LANGUAGE",
  SEARCH_CATEGORIES: "SEARCH_CATEGORIES",
  FLUSH_CATEGORIES: "FLUSH_CATEGORIES",
  SELECT_CATEGORY: "SELECT_CATEGORY",
  SELECT_SUB_CATEGORY: "SELECT_SUB_CATEGORY",
  SELECTED_CATEGORY: "SELECTED_CATEGORY",
  ADD_PRODUCT_CATEGORY: "ADD_PRODUCT_CATEGORY",

  ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
  ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
  ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",

  ADD_PRODUCT_REVIEW_REQUEST: "ADD_PRODUCT_REVIEW_REQUEST",
  ADD_PRODUCT_REVIEW_SUCCESS: "ADD_PRODUCT_REVIEW_SUCCESS",
  ADD_PRODUCT_REVIEW_FAILURE: "ADD_PRODUCT_REVIEW_FAILURE",

  ADD_PRODUCT_IMAGES_REQUEST: "ADD_PRODUCT_IMAGES_REQUEST",
  ADD_PRODUCT_IMAGES_SUCCESS: "ADD_PRODUCT_IMAGES_SUCCESS",
  ADD_PRODUCT_IMAGES_FAILURE: "ADD_PRODUCT_IMAGES_FAILURE",

  ADD_PRODUCT_VIDEOS_REQUEST: "ADD_PRODUCT_VIDEOS_REQUEST",
  ADD_PRODUCT_VIDEOS_SUCCESS: "ADD_PRODUCT_VIDEOS_SUCCESS",
  ADD_PRODUCT_VIDEOS_FAILURE: "ADD_PRODUCT_VIDEOS_FAILURE",

  DROP_PRODUCT_IMAGES: "DROP_PRODUCT_IMAGES",
  PRODUCT_IMAGES_REMOVE: "PRODUCT_IMAGES_REMOVE",
  FLUSH_PRODUCT_IMAGES: "FLUSH_PRODUCT_IMAGES",
  FLUSH_ADD_PRODUCT: "FLUSH_ADD_PRODUCT",
  FLUSH_PRODUCT: "FLUSH_PRODUCT",
  SELECT_SORT_FILTER: "SELECT_SORT_FILTER",
  SELECT_PRICE_FILTER: "SELECT_PRICE_FILTER",
  SELECT_RATING_FILTER: "SELECT_RATING_FILTER",
  SELECT_CATEGORY_FILTER: "SELECT_CATEGORY_FILTER"
};

export default actionTypes;
