export const actionTypes = {
  QUANTITY_INCREMENT: "QUANTITY_INCREMENT",
  QUANTITY_DECREMENT: "QUANTITY_DECREMENT",
  GET_CATEGORY_REQUEST: "GET_CATEGORY_REQUEST",
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  GET_CATEGORY_FAILURE: "GET_CATEGORY_FAILURE",
  SELECTED_PRODUCT_CATEGORY: "SELECTED_PRODUCT_CATEGORY",
  SELECT_PRODUCT_LANGUAGE: "SELECT_PRODUCT_LANGUAGE",
  SEARCH_CATEGORIES: "SEARCH_CATEGORIES",
  FLUSH_CATEGORIES: "FLUSH_CATEGORIES",
  SELECT_CATEGORY: "SELECT_CATEGORY",
  ADD_PRODUCT_CATEGORY: "ADD_PRODUCT_CATEGORY"
};

export default actionTypes;
