export const actionTypes = {
  QUANTITY_INCREMENT: "QUANTITY_INCREMENT",
  QUANTITY_DECREMENT: "QUANTITY_DECREMENT",

  GET_CATEGORY_REQUEST: "GET_CATEGORY_REQUEST",
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  GET_CATEGORY_FAILURE: "GET_CATEGORY_FAILURE",

  GET_CATEGORIES_REQUEST: "GET_CATEGORIES_REQUEST",
  GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
  GET_CATEGORIES_FAILURE: "GET_CATEGORIES_FAILURE",

  GET_CATEGORY_PRODUCTS_REQUEST: "GET_CATEGORY_PRODUCTS_REQUEST",
  GET_CATEGORY_PRODUCTS_SUCCESS: "GET_CATEGORY_PRODUCTS_SUCCESS",
  GET_CATEGORY_PRODUCTS_FAILURE: "GET_CATEGORY_PRODUCTS_FAILURE",

  SELECTED_PRODUCT_CATEGORY: "SELECTED_PRODUCT_CATEGORY",
  SELECT_PRODUCT_LANGUAGE: "SELECT_PRODUCT_LANGUAGE",
  SEARCH_CATEGORIES: "SEARCH_CATEGORIES",
  FLUSH_CATEGORIES: "FLUSH_CATEGORIES",
  SELECT_CATEGORY: "SELECT_CATEGORY",
  SELECTED_CATEGORY: "SELECTED_CATEGORY",
  ADD_PRODUCT_CATEGORY: "ADD_PRODUCT_CATEGORY",

  ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
  ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
  ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",

  ADD_PRODUCT_IMAGES_REQUEST: "ADD_PRODUCT_IMAGES_REQUEST",
  ADD_PRODUCT_IMAGES_SUCCESS: "ADD_PRODUCT_IMAGES_SUCCESS",
  ADD_PRODUCT_IMAGES_FAILURE: "ADD_PRODUCT_IMAGES_FAILURE",

  DROP_PRODUCT_IMAGES: "DROP_PRODUCT_IMAGES",
  PRODUCT_IMAGES_REMOVE: "PRODUCT_IMAGES_REMOVE",
  FLUSH_PRODUCT_IMAGES: "FLUSH_PRODUCT_IMAGES",
  FLUSH_ADD_PRODUCT: "FLUSH_ADD_PRODUCT"
};

export default actionTypes;
