export const ActionTypes = {
  TOGGLE_LOGIN_FORM: "TOGGLE_LOGIN_FORM",

  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  AUTH_STATUS_REQUEST: "AUTH_STATUS_REQUEST",
  AUTH_STATUS_SUCCESS: "AUTH_STATUS_SUCCESS",
  AUTH_STATUS_FAILURE: "AUTH_STATUS_FAILURE",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  USERNAME_REQUEST: "USERNAME_REQUEST",
  USERNAME_SUCCESS: "USERNAME_SUCCESS",
  USERNAME_FAILURE: "USERNAME_FAILURE",

  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",

  VERIFY_EMAIL_REQUEST: "VERIFY_EMAIL_REQUEST",
  VERIFY_EMAIL_SUCCESS: "VERIFY_EMAIL_SUCCESS",
  VERIFY_EMAIL_FAILURE: "VERIFY_EMAIL_FAILURE",

  SOCIAL_LOGIN_REQUEST: "SOCIAL_LOGIN_REQUEST",
  SOCIAL_LOGIN_SUCCESS: "SOCIAL_LOGIN_SUCCESS",
  SOCIAL_LOGIN_FAILURE: "SOCIAL_LOGIN_FAILURE",

  SOCIAL_LOGIN_TOKEN_REQUEST: "SOCIAL_LOGIN_TOKEN_REQUEST",
  SOCIAL_LOGIN_TOKEN_SUCCESS: "SOCIAL_LOGIN_TOKEN_SUCCESS",
  SOCIAL_LOGIN_TOKEN_FAILURE: "SOCIAL_LOGIN_TOKEN_FAILURE",

  PASSWORD_RESET_EMAIL_REQUEST: "PASSWORD_RESET_EMAIL_REQUEST",
  PASSWORD_RESET_EMAIL_SUCCESS: "PASSWORD_RESET_EMAIL_SUCCESS",
  PASSWORD_RESET_EMAIL_FAILURE: "PASSWORD_RESET_EMAIL_FAILURE",

  PASSWORD_RESET_REQUEST: "PASSWORD_RESET_REQUEST",
  PASSWORD_RESET_SUCCESS: "PASSWORD_RESET_SUCCESS",
  PASSWORD_RESET_FAILURE: "PASSWORD_RESET_FAILURE",

  PASSWORD_CHANGE_REQUEST: "PASSWORD_CHANGE_REQUEST",
  PASSWORD_CHANGE_SUCCESS: "PASSWORD_CHANGE_SUCCESS",
  PASSWORD_CHANGE_FAILURE: "PASSWORD_CHANGE_FAILURE",

  UPDATE_PROFILE_REQUEST: "UPDATE_PROFILE_REQUEST",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
  UPDATE_PROFILE_FAILURE: "UPDATE_PROFILE_FAILURE",

  UPDATE_AVATAR_REQUEST: "UPDATE_AVATAR_REQUEST",
  UPDATE_AVATAR_SUCCESS: "UPDATE_AVATAR_SUCCESS",
  UPDATE_AVATAR_FAILURE: "UPDATE_AVATAR_FAILURE",

  VERIFICATION_EMAIL_REQUEST: "VERIFICATION_EMAIL_REQUEST",
  VERIFICATION_EMAIL_SUCCESS: "VERIFICATION_EMAIL_SUCCESS",
  VERIFICATION_EMAIL_FAILURE: "VERIFICATION_EMAIL_FAILURE",

  GET_USER_PROFILE_REQUEST: "GET_USER_PROFILE_REQUEST",
  GET_USER_PROFILE_SUCCESS: "GET_USER_PROFILE_SUCCESS",
  GET_USER_PROFILE_FAILURE: "GET_USER_PROFILE_FAILURE",

  GET_SELLER_ACTIVE_PLAN_REQUEST: "GET_SELLER_ACTIVE_PLAN_REQUEST",
  GET_SELLER_ACTIVE_PLAN_SUCCESS: "GET_SELLER_ACTIVE_PLAN_SUCCESS",
  GET_SELLER_ACTIVE_PLAN_FAILURE: "GET_SELLER_ACTIVE_PLAN_FAILURE",

  UPLOAD_CERTIFICATE_REQUEST: "UPLOAD_CERTIFICATE_REQUEST",
  UPLOAD_CERTIFICATE_SUCCESS: "UPLOAD_CERTIFICATE_SUCCESS",
  UPLOAD_CERTIFICATE_FAILURE: "UPLOAD_CERTIFICATE_FAILURE",

  UPDATE_CERTIFICATE_REQUEST: "UPDATE_CERTIFICATE_REQUEST",
  UPDATE_CERTIFICATE_SUCCESS: "UPDATE_CERTIFICATE_SUCCESS",
  UPDATE_CERTIFICATE_FAILURE: "UPDATE_CERTIFICATE_FAILURE",

  DELETE_CERTIFICATE_REQUEST: "DELETE_CERTIFICATE_REQUEST",
  DELETE_CERTIFICATE_SUCCESS: "DELETE_CERTIFICATE_SUCCESS",
  DELETE_CERTIFICATE_FAILURE: "DELETE_CERTIFICATE_FAILURE",

  UPLOAD_VIDEO_REQUEST: "UPLOAD_VIDEO_REQUEST",
  UPLOAD_VIDEO_SUCCESS: "UPLOAD_VIDEO_SUCCESS",
  UPLOAD_VIDEO_FAILURE: "UPLOAD_VIDEO_FAILURE",

  FLUSH_STATE: "FLUSH_STATE",

  ADD_NEW_REFERENCE_REQUEST: "ADD_NEW_REFERENCE_REQUEST",
  ADD_NEW_REFERENCE_SUCCESS: "ADD_NEW_REFERENCE_SUCCESS",
  ADD_NEW_REFERENCE_FAILURE: "ADD_NEW_REFERENCE_FAILURE",

  EDIT_REFERENCE_REQUEST: "EDIT_REFERENCE_REQUEST",
  EDIT_REFERENCE_SUCCESS: "EDIT_REFERENCE_SUCCESS",
  EDIT_REFERENCE_FAILURE: "EDIT_REFERENCE_FAILURE"
};

export default ActionTypes;
