export const ActionTypes = {
  toogleLoginForm: "TOGGLE_LOGIN_FORM",
  loginRequest: "LOGIN_REQUEST",
  loginSuccess: "LOGIN_SUCCESS",
  loginFailure: "LOGIN_FAILURE",
  USERNAME_REQUEST: "USERNAME_REQUEST",
  USERNAME_SUCCESS: "USERNAME_SUCCESS",
  USERNAME_FAILURE: "USERNAME_FAILURE",
  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",

  SOCIAL_LOGIN_REQUEST: "SOCIAL_LOGIN_REQUEST",
  SOCIAL_LOGIN_SUCCESS: "SOCIAL_LOGIN_SUCCESS",
  SOCIAL_LOGIN_FAILURE: "SOCIAL_LOGIN_FAILURE",

  SOCIAL_LOGIN_TOKEN_REQUEST: "SOCIAL_LOGIN_TOKEN_REQUEST",
  SOCIAL_LOGIN_TOKEN_SUCCESS: "SOCIAL_LOGIN_TOKEN_SUCCESS",
  SOCIAL_LOGIN_TOKEN_FAILURE: "SOCIAL_LOGIN_TOKEN_FAILURE"
};

export default ActionTypes;
