export const ActionTypes = {
  TOGGLE_LOGIN_FORM: "TOGGLE_LOGIN_FORM",

  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  USERNAME_REQUEST: "USERNAME_REQUEST",
  USERNAME_SUCCESS: "USERNAME_SUCCESS",
  USERNAME_FAILURE: "USERNAME_FAILURE",

  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",

  VERIFY_EMAIL_REQUEST: "VERIFY_EMAIL_REQUEST",
  VERIFY_EMAIL_SUCCESS: "VERIFY_EMAIL_SUCCESS",
  VERIFY_EMAIL_FAILURE: "VERIFY_EMAIL_FAILURE",

  SOCIAL_LOGIN_REQUEST: "SOCIAL_LOGIN_REQUEST",
  SOCIAL_LOGIN_SUCCESS: "SOCIAL_LOGIN_SUCCESS",
  SOCIAL_LOGIN_FAILURE: "SOCIAL_LOGIN_FAILURE",

  SOCIAL_LOGIN_TOKEN_REQUEST: "SOCIAL_LOGIN_TOKEN_REQUEST",
  SOCIAL_LOGIN_TOKEN_SUCCESS: "SOCIAL_LOGIN_TOKEN_SUCCESS",
  SOCIAL_LOGIN_TOKEN_FAILURE: "SOCIAL_LOGIN_TOKEN_FAILURE",

  PASSWORD_RESET_REQUEST: "PASSWORD_RESET_REQUEST",
  PASSWORD_RESET_SUCCESS: "PASSWORD_RESET_SUCCESS",
  PASSWORD_RESET_FAILURE: "PASSWORD_RESET_FAILURE",

  UPDATE_PROFILE_REQUEST: "UPDATE_PROFILE_REQUEST",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
  UPDATE_PROFILE_FAILURE: "UPDATE_PROFILE_FAILURE",

  FLUSH_STATE: "FLUSH_STATE"
};

export default ActionTypes;
