export const ActionTypes = {
  GET_WISHLIST_REQUEST: "GET_WISHLIST_REQUEST",
  GET_WISHLIST_SUCCESS: "GET_WISHLIST_SUCCESS",
  GET_WISHLIST_FAILURE: "GET_WISHLIST_FAILURE",

  REMOVE_WISHLIST_REQUEST: "REMOVE_WISHLIST_REQUEST",
  REMOVE_WISHLIST_SUCCESS: "REMOVE_WISHLIST_SUCCESS",
  REMOVE_WISHLIST_FAILURE: "REMOVE_WISHLIST_FAILURE",

  ADD_TO_WISHLIST_REQUEST: "ADD_TO_WISHLIST_REQUEST",
  ADD_TO_WISHLIST_SUCCESS: "ADD_TO_WISHLIST_SUCCESS",
  ADD_TO_WISHLIST_FAILURE: "ADD_TO_WISHLIST_FAILURE"
};

export default ActionTypes;
