export const ActionTypes = {
  GET_WISHLIST_REQUEST: "GET_WISHLIST_REQUEST",
  GET_WISHLIST_SUCCESS: "GET_WISHLIST_SUCCESS",
  GET_WISHLIST_FAILURE: "GET_WISHLIST_FAILURE",

  REMOVE_WISHLIST_REQUEST: "REMOVE_WISHLIST_REQUEST",
  REMOVE_WISHLIST_SUCCESS: "REMOVE_WISHLIST_SUCCESS",
  REMOVE_WISHLIST_FAILURE: "REMOVE_WISHLIST_FAILURE",

  ADD_TO_WISHLIST_REQUEST: "ADD_TO_WISHLIST_REQUEST",
  ADD_TO_WISHLIST_SUCCESS: "ADD_TO_WISHLIST_SUCCESS",
  ADD_TO_WISHLIST_FAILURE: "ADD_TO_WISHLIST_FAILURE",

  VERIFY_EMAIL_REQUEST: "VERIFY_EMAIL_REQUEST",
  VERIFY_EMAIL_SUCCESS: "VERIFY_EMAIL_SUCCESS",
  VERIFY_EMAIL_FAILURE: "VERIFY_EMAIL_FAILURE",

  GET_BUYER_LOCATION_REQUEST: "GET_BUYER_LOCATION_REQUEST",
  GET_BUYER_LOCATION_SUCCESS: "GET_BUYER_LOCATION_SUCCESS",
  GET_BUYER_LOCATION_FAILURE: "GET_BUYER_LOCATION_FAILURE",

  SHOW_BUYER_MAP: "SHOW_BUYER_MAP",
  ADD_BUYER_LOCATION: "ADD_BUYER_LOCATION"
};

export default ActionTypes;
