export const ActionTypes = {
  GET_ORDERS_REQUEST: "GET_ORDERS_REQUEST",
  GET_ORDERS_SUCCESS: "GET_ORDERS_SUCCESS",
  GET_ORDERS_FAILURE: "GET_ORDERS_FAILURE",

  ADD_PAYMENT_REQUEST: "ADD_PAYMENT_REQUEST",
  ADD_PAYMENT_SUCCESS: "ADD_PAYMENT_SUCCESS",
  ADD_PAYMENT_FAILURE: "ADD_PAYMENT_FAILURE",

  CANCEL_ORDER_REQUEST: "CANCEL_ORDER_REQUEST",
  CANCEL_ORDER_SUCCESS: "CANCEL_ORDER_SUCCESS",
  CANCEL_ORDER_FAILURE: "CANCEL_ORDER_FAILURE",

  GET_ORDER_TRANSACTIONS_REQUEST: "GET_ORDER_TRANSACTIONS_REQUEST",
  GET_ORDER_TRANSACTIONS_SUCCESS: "GET_ORDER_TRANSACTIONS_SUCCESS",
  GET_ORDER_TRANSACTIONS_FAILURE: "GET_ORDER_TRANSACTIONS_FAILURE"
};

export default ActionTypes;
