export const ActionTypes = {
  GET_ORDERS_REQUEST: "GET_ORDERS_REQUEST",
  GET_ORDERS_SUCCESS: "GET_ORDERS_SUCCESS",
  GET_ORDERS_FAILURE: "GET_ORDERS_FAILURE",
  ADD_PAYMENT_REQUEST: "ADD_PAYMENT_REQUEST",
  ADD_PAYMENT_SUCCESS: "ADD_PAYMENT_SUCCESS",
  ADD_PAYMENT_FAILURE: "ADD_PAYMENT_FAILURE"
};

export default ActionTypes;
