export const actionTypes = {
  SEARCH_CATEGORIES_REQUEST: "SEARCH_CATEGORIES_REQUEST",
  SEARCH_CATEGORIES_SUCCESS: "SEARCH_CATEGORIES_SUCCESS",
  SEARCH_CATEGORIES_FAILURE: "SEARCH_CATEGORIES_FAILURE",
  SELECT_CATEGORIES: "SELECT_CATEGORIES",
  FLUSH_SUGGESTION: "FLUSH_SUGGESTION"
};

export default actionTypes;
