export const ActionTypes = {
  GET_PLANS_REQUEST: "GET_PLANS_REQUEST",
  GET_PLANS_SUCCESS: "GET_PLANS_SUCCESS",
  GET_PLANS_FAILURE: "GET_PLANS_FAILURE",

  GET_SERVICES_REQUEST: "GET_SERVICES_REQUEST",
  GET_SERVICES_SUCCESS: "GET_SERVICES_SUCCESS",
  GET_SERVICES_FAILURE: "GET_SERVICES_FAILURE",

  SELECT_PLANS: "SELECT_PLANS",

  ADD_PAYMENT_REQUEST: "ADD_PAYMENT_REQUEST",
  ADD_PAYMENT_SUCCESS: "ADD_PAYMENT_SUCCESS",
  ADD_PAYMENT_FAILURE: "ADD_PAYMENT_FAILURE",
};
export default ActionTypes;
