export const ActionTypes = {
  GET_CART_PRODUCTS_REQUEST: "GET_CART_PRODUCTS_REQUEST",
  GET_CART_PRODUCTS_SUCCESS: "GET_CART_PRODUCTS_SUCCESS",
  GET_CART_PRODUCTS_FAILURE: "GET_CART_PRODUCTS_FAILURE",

  GET_CART_PRODUCTS_TOTALS_REQUEST: "GET_CART_PRODUCTS_TOTALS_REQUEST",
  GET_CART_PRODUCTS_TOTALS_SUCCESS: "GET_CART_PRODUCTS_TOTALS_SUCCESS",
  GET_CART_PRODUCTS_TOTALS_FAILURE: "GET_CART_PRODUCTS_TOTALS_FAILURE",

  CART_QUANTITY_INCREMENT: "CART_QUANTITY_INCREMENT",
  CART_QUANTITY_DECREMENT: "CART_QUANTITY_DECREMENT",

  QUANTITY_INCREMENT_REQUEST: "QUANTITY_INCREMENT_REQUEST",
  QUANTITY_INCREMENT_SUCCESS: "QUANTITY_INCREMENT_SUCCESS",
  QUANTITY_INCREMENT_FAILURE: "QUANTITY_INCREMENT_FAILURE",

  QUANTITY_DECREMENT_REQUEST: "QUANTITY_DECREMENT_REQUEST",
  QUANTITY_DECREMENT_SUCCESS: "QUANTITY_DECREMENT_SUCCESS",
  QUANTITY_DECREMENT_FAILURE: "QUANTITY_DECREMENT_FAILURE",

  ADD_TO_CART: "ADD_TO_CART",
  ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",

  ADD_TO_WISHLIST_REQUEST: "ADD_TO_WISHLIST_REQUEST",
  ADD_TO_WISHLIST_SUCCESS: "ADD_TO_WISHLIST_SUCCESS",
  ADD_TO_WISHLIST_FAILURE: "ADD_TO_WISHLIST_FAILURE",

  REMOVE_CART_PRODUCT_REQUEST: "REMOVE_CART_PRODUCT_REQUEST",
  REMOVE_CART_PRODUCT_SUCCESS: "REMOVE_CART_PRODUCT_SUCCESS",
  REMOVE_CART_PRODUCT_FAILURE: "REMOVE_CART_PRODUCT_FAILURE"
};
export default ActionTypes;
