export const ActionTypes = {
  GET_PRODUCTS_REQUEST: "GET_PRODUCTS_REQUEST",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAILURE: "GET_PRODUCTS_FAILURE",

  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",

  GET_PRODUCT_IMAGE_REQUEST: "GET_PRODUCT_IMAGE_REQUEST",
  GET_PRODUCT_IMAGE_SUCCESS: "GET_PRODUCT_IMAGE_SUCCESS",
  GET_PRODUCT_IMAGE_FAILURE: "GET_PRODUCT_IMAGE_FAILURE",

  GET_CATEGORIES_REQUEST: "GET_CATEGORIES_REQUEST",
  GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
  GET_CATEGORIES_FAILURE: "GET_CATEGORIES_FAILURE",

  UPDATE_PRODUCT_REQUEST: "UPDATE_PRODUCT_REQUEST",
  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_FAILURE: "UPDATE_PRODUCT_FAILURE",

  DELETE_PRODUCT_IMAGE_REQUEST: "DELETE_PRODUCT_IMAGE_REQUEST",
  DELETE_PRODUCT_IMAGE_SUCCESS: "DELETE_PRODUCT_IMAGE_SUCCESS",
  DELETE_PRODUCT_IMAGE_FAILURE: "DELETE_PRODUCT_IMAGE_FAILURE",

  DELETE_PRODUCT_OPTIMISTIC: "DELETE_PRODUCT_OPTIMISTIC",
  DELETE_PRODUCT_REQUEST: "DELETE_PRODUCT_REQUEST",
  DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_FAILURE: "DELETE_PRODUCT_FAILURE",

  GET_LOCATION_REQUEST: "GET_LOCATION_REQUEST",
  GET_LOCATION_SUCCESS: "GET_LOCATION_SUCCESS",
  GET_LOCATION_FAILURE: "GET_LOCATION_FAILURE",

  GET_CATEGORY_REQUEST: "GET_CATEGORY_REQUEST",
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  GET_CATEGORY_FAILURE: "GET_CATEGORY_FAILURE",

  GET_PRODUCT_REVIEW_REQUEST: "GET_PRODUCT_REVIEW_REQUEST",
  GET_PRODUCT_REVIEW_SUCCESS: "GET_PRODUCT_REVIEW_SUCCESS",
  GET_PRODUCT_REVIEW_FAILURE: "GET_PRODUCT_REVIEW_FAILURE",

  EDIT_PRODUCT_REVIEW_REQUEST: "EDIT_PRODUCT_REVIEW_REQUEST",
  EDIT_PRODUCT_REVIEW_SUCCESS: "EDIT_PRODUCT_REVIEW_SUCCESS",
  EDIT_PRODUCT_REVIEW_FAILURE: "EDIT_PRODUCT_REVIEW_FAILURE",

  CHANGE_PRODUCT_STATUS_REVIEW_REQUEST: "CHANGE_PRODUCT_STATUS_REVIEW_REQUEST",
  CHANGE_PRODUCT_STATUS_REVIEW_SUCCESS: "CHANGE_PRODUCT_STATUS_REVIEW_SUCCESS",
  CHANGE_PRODUCT_STATUS_REVIEW_FAILURE: "CHANGE_PRODUCT_STATUS_REVIEW_FAILURE",

  SHOW_MAP: "SHOW_MAP"
};
export default ActionTypes;
