export const ActionTypes = {
  GET_PRODUCTS_REQUEST: "GET_PRODUCTS_REQUEST",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAILURE: "GET_PRODUCTS_FAILURE",

  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",

  GET_PRODUCT_IMAGE_REQUEST: "GET_PRODUCT_IMAGE_REQUEST",
  GET_PRODUCT_IMAGE_SUCCESS: "GET_PRODUCT_IMAGE_SUCCESS",
  GET_PRODUCT_IMAGE_FAILURE: "GET_PRODUCT_IMAGE_FAILURE",

  UPDATE_PRODUCT_REQUEST: "UPDATE_PRODUCT_REQUEST",
  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_FAILURE: "UPDATE_PRODUCT_FAILURE",

  DELETE_PRODUCT_IMAGE_REQUEST: "DELETE_PRODUCT_IMAGE_REQUEST",
  DELETE_PRODUCT_IMAGE_SUCCESS: "DELETE_PRODUCT_IMAGE_SUCCESS",
  DELETE_PRODUCT_IMAGE_FAILURE: "DELETE_PRODUCT_IMAGE_FAILURE",

  DELETE_PRODUCT_OPTIMISTIC: "DELETE_PRODUCT_OPTIMISTIC",
  DELETE_PRODUCT_REQUEST: "DELETE_PRODUCT_REQUEST",
  DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_FAILURE: "DELETE_PRODUCT_FAILURE",

  GET_LOCATION_REQUEST: "GET_LOCATION_REQUEST",
  GET_LOCATION_SUCCESS: "GET_LOCATION_SUCCESS",
  GET_LOCATION_FAILURE: "GET_LOCATION_FAILURE",

  GET_CATEGORY_REQUEST: "GET_CATEGORY_REQUEST",
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  GET_CATEGORY_FAILURE: "GET_CATEGORY_FAILURE",

  SHOW_MAP: "SHOW_MAP"
};
export default ActionTypes;
