export const ActionTypes = {
  PASSWORD_CHANGE_REQUEST: "PASSWORD_CHANGE_REQUEST",
  PASSWORD_CHANGE_SUCCESS: "PASSWORD_CHANGE_SUCCESS",
  PASSWORD_CHANGE_FAILURE: "PASSWORD_CHANGE_FAILURE",

  UPDATE_PROFILE_REQUEST: "UPDATE_PROFILE_REQUEST",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
  UPDATE_PROFILE_FAILURE: "UPDATE_PROFILE_FAILURE",

  CHANGE_PROFILE_REQUEST: "CHANGE_PROFILE_REQUEST",
  CHANGE_PROFILE_SUCCESS: "CHANGE_PROFILE_SUCCESS",
  CHANGE_PROFILE_FAILURE: "CHANGE_PROFILE_FAILURE"
};
export default ActionTypes;
