export const ActionTypes = {
  GET_SELLER_ORDERS_REQUEST: "GET_SELLER_ORDERS_REQUEST",
  GET_SELLER_ORDERS_SUCCESS: "GET_SELLER_ORDERS_SUCCESS",
  GET_SELLER_ORDERS_FAILURE: "GET_SELLER_ORDERS_FAILURE",

  CHANGE_ORDERS_STATUS_REQUEST: "CHANGE_ORDERS_STATUS_REQUEST",
  CHANGE_ORDERS_STATUS_SUCCESS: "CHANGE_ORDERS_STATUS_SUCCESS",
  CHANGE_ORDERS_STATUS_FAILURE: "CHANGE_ORDERS_STATUS_FAILURE",

  UPDATE_ORDER_REQUEST: "UPDATE_ORDER_REQUEST",
  UPDATE_ORDER_SUCCESS: "UPDATE_ORDER_SUCCESS",
  UPDATE_ORDER_FAILURE: "UPDATE_ORDER_FAILURE",

  GET_SELLER_ORDER_TRANSACTIONS_REQUEST:
    "GET_SELLER_ORDER_TRANSACTIONS_REQUEST",
  GET_SELLER_ORDER_TRANSACTIONS_SUCCESS:
    "GET_SELLER_ORDER_TRANSACTIONS_SUCCESS",
  GET_SELLER_ORDER_TRANSACTIONS_FAILURE:
    "GET_SELLER_ORDER_TRANSACTIONS_FAILURE",
  SELECT_ORDER_FILTER: "SELECT_ORDER_FILTER"
};

export default ActionTypes;
