export const ActionTypes = {
  GET_SELLER_ORDERS_REQUEST: "GET_SELLER_ORDERS_REQUEST",
  GET_SELLER_ORDERS_SUCCESS: "GET_SELLER_ORDERS_SUCCESS",
  GET_SELLER_ORDERS_FAILURE: "GET_SELLER_ORDERS_FAILURE",

  CHANGE_ORDERS_STATUS_REQUEST: "CHANGE_ORDERS_STATUS_REQUEST",
  CHANGE_ORDERS_STATUS_SUCCESS: "CHANGE_ORDERS_STATUS_SUCCESS",
  CHANGE_ORDERS_STATUS_FAILURE: "CHANGE_ORDERS_STATUS_FAILURE"
};

export default ActionTypes;
