export const ActionTypes = {
  GET_SELLER_PROFILE_REQUEST: "GET_SELLER_PROFILE_REQUEST",
  GET_SELLER_PROFILE_SUCCESS: "GET_SELLER_PROFILE_SUCCESS",
  GET_SELLER_PROFILE_FAILURE: "GET_SELLER_PROFILE_FAILURE",

  GET_SELLER_PRODUCTS_REQUEST: "GET_SELLER_PRODUCTS_REQUEST",
  GET_SELLER_PRODUCTS_SUCCESS: "GET_SELLER_PRODUCTS_SUCCESS",
  GET_SELLER_PRODUCTS_FAILURE: "GET_SELLER_PRODUCTS_FAILURE"
};

export default ActionTypes;
