export const ActionTypes = {
  GET_CART_PRODUCTS_REQUEST: "GET_CART_PRODUCTS_REQUEST",
  GET_CART_PRODUCTS_SUCCESS: "GET_CART_PRODUCTS_SUCCESS",
  GET_CART_PRODUCTS_FAILURE: "GET_CART_PRODUCTS_FAILURE",

  GET_SHIPPING_OPTIONS_REQUEST: "GET_SHIPPING_OPTIONS_REQUEST",
  GET_SHIPPING_OPTIONS_SUCCESS: "GET_SHIPPING_OPTIONS_SUCCESS",
  GET_SHIPPING_OPTIONS_FAILURE: "GET_SHIPPING_OPTIONS_FAILURE",

  ADD_ORDER_REQUEST: "ADD_ORDER_REQUEST",
  ADD_ORDER_SUCCESS: "ADD_ORDER_SUCCESS",
  ADD_ORDER_FAILURE: "ADD_ORDER_FAILURE",

  SAVE_SHIPPING_ADDRESS: "SAVE_SHIPPING_ADDRESS",
  FLUSH_ORDER: "FLUSH_ORDER",
  SELECT_SHIPPING_OPTION: "SELECT_SHIPPING_OPTION"
};
export default ActionTypes;
