export const actionTypes = {
  GET_CATEGORIES_REQUEST: "GET_CATEGORIES_REQUEST",
  GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
  GET_CATEGORIES_FAILURE: "GET_CATEGORIES_FAILURE",

  GET_CATEGORY_PRODUCTS_REQUEST: "GET_CATEGORY_PRODUCTS_REQUEST",
  GET_CATEGORY_PRODUCTS_SUCCESS: "GET_CATEGORY_PRODUCTS_SUCCESS",
  GET_CATEGORY_PRODUCTS_FAILURE: "GET_CATEGORY_PRODUCTS_FAILURE",

  GET_TOP_BANNERS_REQUEST: "GET_TOP_BANNERS_REQUEST",
  GET_TOP_BANNERS_SUCCESS: "GET_TOP_BANNERS_SUCCESS",
  GET_TOP_BANNERS_FAILURE: "GET_TOP_BANNERS_FAILURE",

  GET_TOP_SUPPLIERS_REQUEST: "GET_TOP_SUPPLIERS_REQUEST",
  GET_TOP_SUPPLIERS_SUCCESS: "GET_TOP_SUPPLIERS_SUCCESS",
  GET_TOP_SUPPLIERS_FAILURE: "GET_TOP_SUPPLIERS_FAILURE",

  GET_CENTER_BANNERS_REQUEST: "GET_CENTER_BANNERS_REQUEST",
  GET_CENTER_BANNERS_SUCCESS: "GET_CENTER_BANNERS_SUCCESS",
  GET_CENTER_BANNERS_FAILURE: "GET_CENTER_BANNERS_FAILURE",

  GET_BOTTOM_BANNERS_REQUEST: "GET_BOTTOM_BANNERS_REQUEST",
  GET_BOTTOM_BANNERS_SUCCESS: "GET_BOTTOM_BANNERS_SUCCESS",
  GET_BOTTOM_BANNERS_FAILURE: "GET_BOTTOM_BANNERS_FAILURE",

  GET_RECENT_VIEW_PRODUCT_REQUEST: "GET_RECENT_VIEW_PRODUCT_REQUEST",
  GET_RECENT_VIEW_PRODUCT_SUCCESS: "GET_RECENT_VIEW_PRODUCT_SUCCESS",
  GET_RECENT_VIEW_PRODUCT_FAILURE: "GET_RECENT_VIEW_PRODUCT_FAILURE"
};

export default actionTypes;
