export const actionTypes = {
  GET_CATEGORY_REQUEST: "GET_CATEGORY_REQUEST",
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  GET_CATEGORY_FAILURE: "GET_CATEGORY_FAILURE",

  GET_QUOTATIONS_REQUEST: "GET_QUOTATIONS_REQUEST",
  GET_QUOTATIONS_SUCCESS: "GET_QUOTATIONS_SUCCESS",
  GET_QUOTATIONS_FAILURE: "GET_QUOTATIONS_FAILURE",

  GET_BUYER_QUOTATIONS_REQUEST: "GET_BUYER_QUOTATIONS_REQUEST",
  GET_BUYER_QUOTATIONS_SUCCESS: "GET_BUYER_QUOTATIONS_SUCCESS",
  GET_BUYER_QUOTATIONS_FAILURE: "GET_BUYER_QUOTATIONS_FAILURE",

  SEARCH_QUOTATIONS_REQUEST: "SEARCH_QUOTATIONS_REQUEST",
  SEARCH_QUOTATIONS_SUCCESS: "SEARCH_QUOTATIONS_SUCCESS",
  SEARCH_QUOTATIONS_FAILURE: "SEARCH_QUOTATIONS_FAILURE",

  SUBMIT_QUOTE_REQUEST: "SUBMIT_QUOTE_REQUEST",
  SUBMIT_QUOTE_SUCCESS: "SUBMIT_QUOTE_SUCCESS",
  SUBMIT_QUOTE_FAILURE: "SUBMIT_QUOTE_FAILURE",

  SELECT_FILTER: "SELECT_FILTER",

  ADD_QUOTATION_REQUEST: "ADD_QUOTATION_REQUEST",
  ADD_QUOTATION_SUCCESS: "ADD_QUOTATION_SUCCESS",
  ADD_QUOTATION_FAILURE: "ADD_QUOTATION_FAILURE",

  ADD_QUOTATION_IMAGES_REQUEST: "ADD_QUOTATION_IMAGES_REQUEST",
  ADD_QUOTATION_IMAGES_SUCCESS: "ADD_QUOTATION_IMAGES_SUCCESS",
  ADD_QUOTATION_IMAGES_FAILURE: "ADD_QUOTATION_IMAGES_FAILURE",

  DROP_QUOTATION_IMAGES: "DROP_QUOTATION_IMAGES",
  REMOVE_QUOTATION_IMAGES: "REMOVE_QUOTATION_IMAGES",
  FLUSH_QUOTATION_IMAGES: "FLUSH_QUOTATION_IMAGES",
  FLUSH_ADD_QUOTATION: "FLUSH_ADD_QUOTATION",

  DELETE_QUOTATION_IMAGES_REQUEST: "DELETE_QUOTATION_IMAGES_REQUEST",
  DELETE_QUOTATION_IMAGES_SUCCESS: "DELETE_QUOTATION_IMAGES_SUCCESS",
  DELETE_QUOTATION_IMAGES_FAILURE: "DELETE_QUOTATION_IMAGES_FAILURE"
};

export default actionTypes;
